# Generated by Django 2.2.13 on 2021-05-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
